### ISSUE TITLE
download DOCX file for all webpages.

### ISSUE THREAD

**Issue by veillette** [veillette/hands-on#4]
Through github, generate a docx for all sections of the textbook using

```
myst build --docx
```
and

create a download button that would appear in the nav bar.

**Comment by veillette** [comment]
We need a frontmatter, on every chapter, that would look like  

```
---
title: Measurement and Uncertainty
exports:
  - format: md
    output: exports/chapter2.md
  - format: docx
    template: curvenote
    output: exports/chapter2.docx
  - format: pdf
    template: lapreprint-typst
    output: exports/chapter2.pdf
downloads:
  - file: ./exports/chapter2.pdf
    title: PDF
  - file: ./exports/chapter2.docx
    title: docx
  - file: ./exports/chapter2.md
    title: markdown
---

````
